# Generated by Django 3.2.5 on 2021-09-16 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20210916_1225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='nombre_achat',
        ),
    ]
