# Generated by Django 3.2.5 on 2021-09-16 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_remove_customer_nombre_achat'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='achat',
            field=models.IntegerField(default=0),
        ),
    ]
