# Generated by Django 3.2.5 on 2021-10-01 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_customer_achat'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='e_mail',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
